# Generated by Django 2.1.7 on 2019-03-30 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='dt_finish',
            field=models.DateTimeField(null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='dt_start',
            field=models.DateTimeField(null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='fl',
            field=models.BooleanField(default=True, verbose_name='Физическое лицо?'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='inn',
            field=models.CharField(max_length=100, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='site',
            field=models.CharField(max_length=100, verbose_name='Веб-сайт'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='dt',
            field=models.DateTimeField(null=True, verbose_name='Крайний срок выполнения задания'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EventModel', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Казвание'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PartnerModel', verbose_name='Картнер'),
        ),
    ]
