# Generated by Django 2.1.7 on 2019-03-30 10:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190330_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
