# Generated by Django 2.1.7 on 2019-03-30 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20190330_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_phys', models.BooleanField(blank=True, default=True, verbose_name='Физическое лицо?')),
                ('is_pathner', models.BooleanField(blank=True, default=True, verbose_name='Партнер?')),
                ('is_volon', models.BooleanField(blank=True, default=False, verbose_name='Волонтер?')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='Физическое лицо?')),
                ('inn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Веб-сайт')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое описание')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProfileModel', verbose_name='Партнер'),
        ),
        migrations.DeleteModel(
            name='PartnerModel',
        ),
    ]
