# Generated by Django 2.1.7 on 2019-03-30 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20190330_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_phys', models.BooleanField(blank=True, default=True, verbose_name='Физическое лицо?')),
                ('is_pathner', models.BooleanField(blank=True, default=True, verbose_name='Партнер?')),
                ('is_volon', models.BooleanField(blank=True, default=False, verbose_name='Волонтер?')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='Сотрудник')),
                ('is_owner', models.BooleanField(blank=True, default=False, verbose_name='Организатор')),
                ('inn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Веб-сайт')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое описание')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProfileModel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ProfileModel', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='perfomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfomer', to='core.ProfileModel'),
        ),
        migrations.DeleteModel(
            name='BaseProfile',
        ),
        migrations.DeleteModel(
            name='ManagerProfile',
        ),
        migrations.DeleteModel(
            name='PartnerProfile',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
        migrations.DeleteModel(
            name='VolunteerProfile',
        ),
    ]
