# Generated by Django 2.1.7 on 2019-03-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190330_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pathner', to='core.ProfileModel', verbose_name='Партнер'),
        ),
    ]
