# Generated by Django 2.1.7 on 2019-03-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190330_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(default='Hello', max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
