# Generated by Django 2.1.7 on 2019-03-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190330_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Постановка'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
