# Generated by Django 2.1.7 on 2019-03-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190330_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'permissions': (('manage', 'Право на редактирование профиля '),), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
