# Generated by Django 2.1.7 on 2019-03-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190330_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(default='не начат', max_length=100, verbose_name='Статус'),
        ),
    ]
