# Generated by Django 2.1.7 on 2019-03-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190330_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='is_partner',
            field=models.BooleanField(blank=True, default=False, verbose_name='Партнер1?'),
        ),
    ]
