# Generated by Django 2.1.7 on 2019-03-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190330_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='is_pathner',
        ),
    ]
