# Generated by Django 2.1.7 on 2019-03-31 01:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_profilemodel_is_pathner'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='snippet',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
