# Generated by Django 2.1.7 on 2019-03-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_eventmodel_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='otch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
    ]
